apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agendu-frontend
  namespace: agendu
  labels:
    app.kubernetes.io/name: agendu-frontend
    app.kubernetes.io/component: frontend
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: registry.franch.in/agendu/front-agendu
              tag: latest
              pullPolicy: Always
            env:
              TZ: "America/Sao_Paulo"
              NODE_ENV: "production"
            ports:
              - name: http
                containerPort: 80
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
        pod:
          imagePullSecrets:
            - name: agendu-registry
    service:
      main:
        ports:
          http:
            port: 80
            targetPort: http
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: agendu.franch.in
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: agendu-frontend-tls
            hosts:
              - agendu.franch.in
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/use-real-ip: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    persistence:
      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /app/.next/cache
