apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calculeinvest-app
  namespace: calculeinvest
  labels:
    app.kubernetes.io/name: calculeinvest-nextjs-app
    app.kubernetes.io/component: frontend
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2" 
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: localhost:5000/calculeinvest
              tag: latest
              pullPolicy: Always
            env:
              TZ: "America/Sao_Paulo"
              NODE_ENV: "production"
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi" 
              limits:
                cpu: "500m" 
                memory: "512Mi"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000 
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: calculeinvest.com
            paths: [{ path: /, pathType: Prefix }]
        tls:
          - secretName: calculeinvest-app-tls
            hosts: [calculeinvest.com]
        annotations: { cert-manager.io/cluster-issuer: "letsencrypt-production" }
    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/data/calculeinvest/app
        advancedMounts:
          main:
            main:
              - path: /app/.next/cache
      uploads:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/data/calculeinvest/uploads
        advancedMounts:
          main:
            main:
              - path: /app/public/uploads
