apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
      initContainers:
        - name: install-avp
          image: ghcr.io/argoproj-labs/argocd-vault-plugin:v1.18.0
          command: ["/bin/sh", "-c"]
          args:
            - cp /usr/local/bin/argocd-vault-plugin /custom-tools/argocd-vault-plugin
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
          env:
            - name: AVP_AUTH_TYPE
              value: kubernetes
            - name: AVP_K8S_ROLE
              value: argocd-repo-server
            - name: AVP_VAULT_ADDR
              value: https://vault.example.com
