apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: registry
  namespace: devops
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: registry
              tag: "2"
            env:
              REGISTRY_HTTP_ADDR: ":5000"
              REGISTRY_STORAGE_DELETE_ENABLED: "true"
              REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "/var/lib/registry"
              REGISTRY_AUTH: "htpasswd"
              REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
              REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
            envFrom:
              - secretRef:
                  name: registry-env
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 2Gi
    service:
      main:
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: registry.franch.in
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - registry.franch.in
            secretName: registry-tls
    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/data/registry
        globalMounts:
          - path: /var/lib/registry
      auth:
        enabled: true
        type: secret
        name: registry-htpasswd
        globalMounts:
          - path: /auth/htpasswd
            subPath: htpasswd
            readOnly: true
