apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-cert-manager-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: core
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://github.com/your-org/cluster-k3s.git
    targetRevision: HEAD
    path: kubernetes/core/cert-manager-config
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
