apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cars-scraper
  namespace: argocd
spec:
  project: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: cars
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: "4.1.2"
    helm:
      values: |
        controllers:
          main:
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              main:
                image:
                  repository: registry.franch.in/back-end-car
                  tag: latest
                  pullPolicy: Always
                command:
                  - /bin/scraper
                env:
                  TZ: "America/Sao_Paulo"
                envFrom:
                  - secretRef:
                      name: cars-scraper-env
                resources:
                  requests:
                    cpu: "200m"
                    memory: "512Mi"
                  limits:
                    cpu: "1000m"
                    memory: "1Gi"
            pod:
              imagePullSecrets:
                - name: registry-credentials
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                fsGroup: 1000
        service:
          main:
            enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
