apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: gaming
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2"
      sourceRef: 
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: itzg/minecraft-server
              tag: java21-jdk
            env:
              EULA: "TRUE"
              TYPE: "PAPER"
              VERSION: "1.21.7"
              MEMORY: "1536M"
              MAX_PLAYERS: "5"
              USE_AIKAR_FLAGS: "true"
              ENABLE_AUTOPAUSE: "TRUE"
              AUTOPAUSE_TIMEOUT_EST: "300"
              AUTOPAUSE_TIMEOUT_INIT: "300"
              AUTOPAUSE_TIMEOUT_KN: "600"  
              ENABLE_PROMETHEUS_METRICS: "true"
              AUTOPAUSE_TIMEOUT_STOP: "300"
            resources:
              requests:
                cpu: "250m"
                memory: "1Gi"
              limits:
                cpu: "1500m"
                memory: "2Gi"
            tty: true
            stdin: true
            volumeMounts:
              - name: paper-config
                mountPath: /data/paper.yml
                subPath: paper.yml
              - name: spigot-config
                mountPath: /data/spigot.yml
                subPath: spigot.yml
              - name: bukkit-config
                mountPath: /data/bukkit.yml
                subPath: bukkit.yml
    service:
      main:
        type: LoadBalancer
        ports:
          minecraft:
            enabled: true
            port: 25565
            protocol: TCP
            targetPort: 25565

    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/data/minecraft
        advancedMounts:
          main:
            main:
              - path: /data
      plugins:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/data/minecraft/plugins
        advancedMounts:
          main:
            main:
              - path: /data/plugins

    configMaps:
      paper-config:
        enabled: true
        data:
          paper.yml: |
            settings:
              redstone-implementation: ALTERNATE_CURRENT
            world-settings:
              default:
                async-chunks:
                  enabled: true
                merge-radius:
                  item: 2.5
                  exp: 3.0
                entity-activation-range:
                  animals: 32
                  monsters: 32
                  raiders: 48
                  misc: 16
                max-tick-time:
                  tile: 1000
                  entity: 1000

      spigot-config:
        enabled: true
        data:
          spigot.yml: |
            settings:
              save-user-cache-on-stop-only: true
              late-bind: false
              restart-on-crash: true
            world-settings:
              default:
                mob-spawn-range: 6
                view-distance: 8
                merge-radius:
                  item: 2.5
                  exp: 3.0
                arrow-despawn-rate: 1200
                item-despawn-rate: 6000

      bukkit-config:
        enabled: true
        data:
          bukkit.yml: |
            settings:
              allow-end: true
              warn-on-overload: true
            spawn-limits:
              monsters: 70
              animals: 10
              water-animals: 5
              ambient: 15
            chunk-gc:
              period-in-ticks: 600
            ticks-per:
              animal-spawns: 400
              monster-spawns: 1
              autosave: 6000
